MVCWebApplication/MVCWebApplication/Models/Book.cs
using System.ComponentModel.DataAnnotations;

namespace MVCWebApplication.Models
{
    public class Book
    {
       
        public int BookID { set; get; }
        public String Title { set; get; }
        public float Cost { set; get; }
        public String AuthorName { set; get; }
    }
}

MVCWebApplication/MVCWebApplication/Models/ErrorViewModel.cs
namespace MVCWebApplication.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVCWebApplication/MVCWebApplication/Controllers/CalculatorController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace MVCWebApplication.Controllers
{
    public class CalculatorController : Controller
    {
        // GET: CalculatorController
        public ActionResult Index()
        {
            return View();
        }

       public int Add(int x, int y)
        {
            return x+y;
        }
    }
}

MVCWebApplication/MVCWebApplication/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVCWebApplication.Models;
using System.Diagnostics;
using System.Text;

namespace MVCWebApplication.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IConfiguration _configuration;

        public HomeController(ILogger<HomeController> logger, IConfiguration configuration)
        {
            _configuration = configuration;
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(int x, IFormCollection collection)
        {
            StringBuilder data = new StringBuilder(500);
            data.Append("x: ");
            data.Append(x);
            data.Append(" ");
            data.Append("name");
            data.Append(collection["name"]);
            data.Append(" ");
            data.Append("password");
            data.Append(collection["password"]);
            //foreach(var item in collection)
            //{
            //    data.Append(item.Key);
            //    data.Append(":");
            //    data.Append(item.Value);
            //}
            ViewData["x"] = x;
            //TempData["global_x"] = x; //transfer data between one controller to another controller using TempData[ ]
            
            return View("IndexPost"); 
            // TEMP DATA - is global 
            //view data - to local scope
        }
        public ActionResult DoTask(int? id) // id is nullable values
        {
            if(id.HasValue) // when id is not explicilty given then in url just give controller/action/?id=121 else give controller/action/121 
            {
                ViewData["id"] = id.Value;
            }
            else
            {
                ViewData["id"] = 0;
            }

            return View("DoTask");
        }

        //redirect to Action
        public ActionResult Test() // can we call action using another action ? - no we can't so use RedirectToAction()
        {

            //return View();
            return RedirectToAction("Index");
        }
        public IActionResult GetBook()
        {
            Book b1 = new Book()
            {
                AuthorName = "Hi Ross"
            };
            ViewData["book"] = b1;
            return View();

        }
        [ResponseCache(Duration =15)] // output cache - for a specific duration in seconds
        public IActionResult GetTime()
        {
            String todate = DateTime.Now.ToLongTimeString();
            ViewData["date"] = todate;
            return View();
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        public IActionResult Menu()
        {
            String constring = _configuration.GetConnectionString("DefaultConnection");
            _logger.Log(LogLevel.Information, constring);
            _logger.Log(LogLevel.Information, "Testing"); // logger.log() - writes in file //loglevel.infor - enum
            return View();
        }
        public ActionResult Echo(String name, String city)
        {
            String s1 = "user " + name + " from city " + city;
            ViewData.Add("Data1", s1);
            return View();
        }
        public ActionResult SayHello(String name)
        {
            String s2 = ("hello " + name);
            ViewData.Add("Data1", s2);
            return View("Echo");
        }
    }
}

MVCWebApplication/MVCWebApplication/Controllers/MoviesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace MVCWebApplication.Controllers
{
    public class MoviesController : Controller
    {
        // GET: MoviesController
      public ActionResult Start()
        {
            return View();
        }

    }
}

MVCWebApplication/MVCWebApplication/Controllers/PartialViewController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace MVCWebApplication.Controllers
{
    public class PartialViewController : Controller
    {
        // GET: PartialViewController
        public ActionResult Index()
        {
            return View();
        }

       public ActionResult Tabs()
        {
            ViewData["data1"] = "Tom and Jerry are good friends";
            return View();
        }
    }
}

MVCWebApplication/MVCWebApplication/Views/Home/DoTask.cshtml
@{
    ViewData["Title"] = "DoTask";
}

<h1>DoTask</h1>
<div>
    <h3>ViewDataX : @ViewData["id"] </h3> 
</div>

MVCWebApplication/MVCWebApplication/Views/Home/Echo.cshtml
@{
    ViewData["Title"] = "Echo";
}

<h1>Echo</h1>

@ViewData["Data1"]

MVCWebApplication/MVCWebApplication/Views/Home/GetBook.cshtml
@using MVCWebApplication.Models ;

@{
    ViewData["Title"] = "GetBook";
}

<h1>GetBook</h1>
<div>
    @{
        Book b1 = (Book)ViewData["book"];
    
    @if (b1 != null)
    {
        @b1.AuthorName
    }
    else
    {
        <strong>Book is null</strong>
    }
 }
</div>

MVCWebApplication/MVCWebApplication/Views/Home/GetTime.cshtml
@{
    ViewData["Title"] = "GetTime";
}


<h1>Time : @ViewData["date"]</h1>
<form action="GetTime">
    <input class="btn btn-success" type="submit" value="❤️❤️"/>

</form>

MVCWebApplication/MVCWebApplication/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";

    var parms = new Dictionary<string, string>
    {
        {
            "x",
            "11"
        }
    };
    TempData["globalX"] = 100;
    ViewData["globalY"] = 100;

}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
</div>
<div>
    <div class="col-md-4">
        <form method="post" asp-all-route-data="parms">
            @*Taghelper*@
            <div>
                @Html.Label("name")
                @Html.TextBox("name","Enter Name")
            </div>
            <div>
                @Html.Label("password")
                <input type="text" name="password" placeholder="Enter password" />
            </div>
            <input type="submit" name="btnsubmit" value="Hitme"/>
        </form>

    </div>
</div>

MVCWebApplication/MVCWebApplication/Views/Home/IndexPost.cshtml
@{
    ViewData["Title"] = "IndexPost";
}

<h1>IndexPost</h1>

<div>
    <h3>ViewDataX : @ViewData["X"] </h3>
    <h3>TempDataX : @TempData["globalX"] </h3>
    <h3>ViewDataY : @ViewData["globalY"] </h3>


</div>

MVCWebApplication/MVCWebApplication/Views/Home/Menu.cshtml
@{
    ViewData["Title"] = "Menu";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
</div>
<div class="jumbotron">
    <a asp-action="Echo" asp-route-name ="Reena"
    asp-route-city ="Chennai" >Call Echo </a>
        <a asp-action="SayHello" asp-route-name ="Sabrina">Call SayHello</a>
</div>

MVCWebApplication/MVCWebApplication/Views/Home/SayHello.cshtml
@{
    ViewData["Title"] = "SayHello";
}

<h1>SayHello</h1>
 @ViewData["Data1"]

MVCWebApplication/MVCWebApplication/Views/Movies/Start.cshtml
@{
    ViewData["Title"] = "Start";
}

<div>
    Welcome to Movies

</div>

<partial name ="_MovieList" />
<partial name="_BookList" />

MVCWebApplication/MVCWebApplication/Views/PartialView/ChildList.cshtml
@{
    ViewData["Title"] = "ChildList";
}


<div style="background-color:aquamarine">
    <hr />
    <h1>ChildList</h1>
    <ul>
        <li>Pheobe</li>
        <li>Monica</li>
        <li>Rachel</li>
        <li>Chandler</li>
        <li>Ross</li>
        <li>Joey</li>

    </ul>
</div>

MVCWebApplication/MVCWebApplication/Views/PartialView/ChildViewdata.cshtml
@{
    ViewData["Title"] = "ChildViewdata";
}

<div style="background-color:beige">
    <h1> For ChildViewdata View : @ViewData["data1"]</h1>
</div>

MVCWebApplication/MVCWebApplication/Views/PartialView/Index.cshtml
<div>
    @{
        ViewData["Title"] = "Index";
        var all_route_parms = new Dictionary<string, string>
    {
    {"x","200"},{"y","50"}
    };
    }
    <!--Razor taghelper-->
    <div>
        <a asp-action="Add" asp-controller="Calculator"
           asp-route-x="250" asp-route-y="50">Call Add asp-route</a>
    </div>
    <div>
        <a asp-action="Add" asp-controller="Calculator"
           asp-all-route-data="all_route_parms">Call Add all_route_parms</a>
    </div>

    <!--Html helper-->
    @await Html.PartialAsync("ChildList")
</div>

MVCWebApplication/MVCWebApplication/Views/PartialView/MyView.cshtml
@{
    ViewData["Title"] = "MyView";
}

<hr />
<h1>Andhaman Beaches List</h1>
<ul>
    <li>
        RadhaNagar
    </li>
    <li>Neal Island</li>
    <li>Ross Island</li>
    <li>Wandoor</li>


</ul>
<h1>MyView</h1>

MVCWebApplication/MVCWebApplication/Views/PartialView/Score.cshtml
@{
    ViewData["Title"] = "Score";
}

<div>
    <h1>Score</h1>
    <h3> Score 30 out 100</h3>

</div>

MVCWebApplication/MVCWebApplication/Views/PartialView/Tabs.cshtml
@{
    ViewData["Title"] = "Tabs";
}

<div>
    <!--Tab buttons -->
    <ul id="tabstrip" class=" nav nav-tabs" role="tablist">
        <li class="active">
            <a href ="#_FirstTab" role="tab" data-toggle="tab">Submission</a>
        </li> <!--# is a selector - used to search and locate the html docs -->
        
      
        <li>
            <a href ="#_SecondTab" role="tab" data-toggle="tab">Search</a>
        </li>
  

        <li>
            <a href="#_ThirdTab" role="tab" data-toggle="tab">Comments</a>
        </li>

    </ul>

<!--tab content containers-->
<div class="tab-content">
    <div class="tab-pane fade in action" id="_FirstTab"> 
        <partial name ="Score" /> 
    </div>
        
    <div class="tab-pane fade in action" id="_SecondTab"> 
        <partial name ="ChildList" /> 
    </div>
       
    <div class="tab-pane fade in action" id="_ThirdTab">
        <partial name="Childviewdata" view-data="ViewData" />
    </div>

</div>
</div>
<partial name="Score" />
<partial name="ChildList" />
<partial name ="ChildViewdata" /> 

MVCWebApplication/MVCWebApplication/Views/Shared/_BookList.cshtml
@{
    ViewData["Title"] = "_BookList";
}

<hr />
<h1>_BookList</h1>
<ul>
    <li>Wasted in Engineering</li>
    <li>It happens for a Reason</li>
    <li>The Leader in You</li>
    <li>The One Minute Manager</li>
    <li>jonathan livingston seagull</li>


</ul>
<hr />

MVCWebApplication/MVCWebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCWebApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCWebApplication.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCWebApplication</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MVCWebApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MVCWebApplication/MVCWebApplication/Views/Shared/_MovieList.cshtml
@{
    ViewData["Title"] = "_MovieList";
}

<hr />
<h1>_MovieList</h1>
<ul>
    <li>SpiderMan</li>
    <li>SuperMan</li>
    <li>BatMan</li>

</ul>
<hr />